---
- hosts: "{{playbook_file_name_without_extension}}"
  # Récupération du nom du fichier pour définir les rôles à appeler
  vars:
    playbook_file_name: "{{ (lookup('file', '/proc/self/cmdline') | regex_replace('\u0000',' ')).split()|select('match','^[a-z-_/]*[.]y[a]*ml')|list|first|basename }}"
    playbook_file_name_without_extension: "{{ playbook_file_name | regex_replace('(.*)[.].*$', '\\1') }}"
    role_path: "./{{ playbook_file_name_without_extension }}/{{ playbook_file_name_without_extension }}"
  
  roles:
    - "{{ playbook_file_name_without_extension }}"  # Utilisez le nom du rôle sans extension

  tasks:
    - name: Detection des distribution
      debug:
        var: ansible_facts['os_family']

    - name: Inclure le rôle spécifique à la distribution
      include_role:
        name: "{{ role_path }}-{{ ansible_facts['os_family'] | lower }}"