---
# tasks file for lamp-debian
# tasks file for lamp-alpine
  - name: Install les packages web
    apt:
     name: [ lighttpd ]
     update_cache: true
     state: present

  - name: Install les packages php
    apt:
     name: [ php ]
     update_cache: true
     state: present

  - name: Install les packages mariadb
    apt:
     name: [ mariadb-server, mariadb-client ]
     update_cache: true
     state: present