---
# Désactivation ipv6
- name: Désactivation ipv6
  template: src=./templates/etc.sysctl.conf.j2 dest=/etc/sysctl.conf owner=root group=root mode='0644'

# Configuration ip master
- name: Configuration ip master
  template: src=./templates/master.etc.dhcpdc.conf.j2 dest=/etc/dhcpcd.conf owner=root group=netdev mode='0664'
  when: inventory_hostname in groups["ClusterPiMaster"]

# Configuration ip node
- name: Configuration ip node
  template: src=./templates/node.etc.dhcpdc.conf.j2 dest=/etc/dhcpcd.conf owner=root group=netdev mode='0664'
  when: inventory_hostname in groups["ClusterPiNode"]
  
# Reboot a Linux machine 
- name: Reboot 
  reboot:
    test_command: uptime

# Installation de docker
- name: install docker
  shell: "curl -sSL https://get.docker.com | sudo sh"
  when: inventory_hostname in groups["ClusterPiMaster"]

# Re-autoriser les acces réseau
- name: Re-autoriser les acces réseau
  shell: sudo iptables -P FORWARD ACCEPT
  when: inventory_hostname in groups["ClusterPiMaster"]

# Sauvegarder autorisation réseau
- name: Sauvegarder autorisation réseau
  shell: sudo sh -c 'iptables-save > /etc/iptables/rules.v4'
  when: inventory_hostname in groups["ClusterPiMaster"]
  
# Acces Docker pour l utilisateur
- name: Acces Docker pour l utilisateur
  shell: sudo usermod -aG docker pi
  when: inventory_hostname in groups["ClusterPiMaster"]
  
# Installation de docker
- name: install docker
  shell: "curl -sSL https://get.docker.com | sudo sh"

# Acces Docker pour l utilisateur
- name: Acces Docker pour l utilisateur
  shell: sudo usermod -aG docker pi