# roles/ssh/tasks/main.yml
---
# Inclue le playbook ajuster en fonction de la distribution et la version
- include_tasks: setup-{{ ansible_os_family }}-{{ ansible_distribution_version }}.yml

# - name: Create a user 'johnd' with a home directory
#   ansible.builtin.user:
#     name: sysadmin
#     create_home: yes

- name: restart sshd
  service:
    name: sshd
    state: restarted