---
# Installation des paquets
- name: Installation des PAQUETS
  ansible.builtin.apt:
    name: [openssh-server]
    update_cache: yes
    state: latest
  when: ansible_facts['os_family'] == "Debian"

- name: Vérifier si le répertoire /etc/ssh/sshd_config.d existe
  stat:
    path: /etc/ssh/sshd_config.d
  register: sshd_config_d

- name: Créer le répertoire /etc/ssh/sshd_config.d
  file:
    path: /etc/ssh/sshd_config.d
    state: directory
    mode: '0755'
  when: not sshd_config_d.stat.exists

- name: "SSH - configuration for Debian os family"
  block:
    - name: "SSH - Configuration de sshd"
      ansible.builtin.template:
        src: "{{ role_path }}/templates/{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
        owner: root
        group: root
      loop:
        - { src: "etc.ssh.sshd_config.j2", dest: "/etc/ssh/sshd_config", mode: "0600" }
        - { src: "etc.ssh.banner.j2", dest: "/etc/ssh/banner", mode: "0600", cis: Ensure SSH warning banner is configured }
  become: true
  ignore_errors: true
  notify: restart sshd
  when: ansible_facts['os_family'] == "Debian"