---
####################################################
##              Configurer Kerberos               ##
####################################################
- name: Configur Kerberos
  template:
    src: etc.krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: '0644'

- name: Reboot the system
  reboot:
    reboot_timeout: 300
    pre_reboot_delay: 10
    post_reboot_delay: 30

####################################################
##                Configurer Samba                ##
####################################################
- name: Supprimer le fichier smb.conf
  file:
    path: /etc/samba/smb.conf
    state: absent

- name: Configurer Samba avec le rôle de contrôleur de domaine
  command: samba-tool domain join {{ realm|lower }} DC -U administrator --realm={{ realm|upper }} -W {{ domain|upper }}

- name: Reconfigurer la résolution DNS
  template:
    src: etc.resolv.conf.j2
    dest: /etc/resolv.conf