---
# tasks file for lamp-alpine
  - name: Install les packages web
    apk:
     name: [ lighttpd ]
     update_cache: true
     state: present

  - name: Install les packages php
    apk:
     name: [ php ]
     update_cache: true
     state: present

  - name: Install les packages mariadb
    apk:
     name: [ mariadb, mariadb-client ]
     update_cache: true
     state: present