---
# tasks file for zabbix-server
- name: Installation des PAQUETS wget, apache2, mariadb-server
  apt:
    pkg: [wget, apache2, mariadb-server]
    update_cache: yes
    state: latest

- name: Telechargement de zabbix-server
  get_url: url=https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-1+debian11_all.deb dest=/tmp

- name: dpkg de zabbix-release_6.0-1+debian11_all.deb
  shell: dpkg -i /tmp/zabbix-release_6.0-1+debian11_all.deb

- name: Installation des PAQUETS zabbix-server-mysql, zabbix-frontend-php, zabbix-apache-conf, zabbix-sql-scripts, zabbix-agent
  apt:
    pkg: [zabbix-server-mysql, zabbix-frontend-php, zabbix-apache-conf, zabbix-sql-scripts, zabbix-agent]
    update_cache: yes
    state: latest

- name: Creation de la basse de donnee '{{ mysqlDatabaseName }}'
  shell: sudo mysql -u "root" -Bse "CREATE DATABASE {{ mysqlDatabaseName }} character set utf8mb4 collate utf8mb4_bin; CREATE USER {{ mysqlUser }}@localhost IDENTIFIED BY '{{ mysqlPassword }}'; GRANT ALL PRIVILEGES ON {{ mysqlDatabaseName }}.* TO {{ mysqlUser }}@localhost; FLUSH PRIVILEGES;"

- name: Creation de la basse de donnee '{{ mysqlDatabaseName }}'
  shell: zcat /usr/share/doc/zabbix-sql-scripts/mysql/server.sql.gz | mysql -u{{ mysqlUser }} -p{{ mysqlPassword }} {{ mysqlDatabaseName }}

- name: Configuration de /etc/zabbix/zabbix_server.conf
  shell: sed -i 's/.*DBPassword*/DBPassword={{ mysqlPassword }}/g' /etc/zabbix/zabbix_server.conf

- name: Activation & Redémarrage du services zabbix-server
  systemd: state=restarted name=zabbix-server enabled=yes masked=no

- name: Activation & Redémarrage du services zabbix-agent
  systemd: state=restarted name=zabbix-agent enabled=yes masked=no

- name: Activation & Redémarrage du services apache2
  systemd: state=restarted name=apache2 enabled=yes masked=no
