---
- name: Inclure les tâches spécifiques pour les autres distributions
  include_tasks: setup-{{ ansible_os_family }}-{{ ansible_distribution_version }}.yml
  when: ansible_distribution != 'Alpine'

- name: Inclure les tâches spécifiques pour Alpine
  include_tasks: setup-{{ ansible_os_family }}-{{ ansible_distribution_version.split('.')[:2] | join('.') }}.yml
  when: ansible_distribution == 'Alpine'