---
# Installation des paquets
- name: Installation des PAQUETS
  ansible.builtin.apt:
    pkg: [squid, ufw, rsync]
    update_cache: yes
    state: latest
  when: ansible_facts['os_family'] == "Debian"

# Add Firewall rule
- name: "SQUID - configuration for Debian os family"
  block:
    - name: Régle du Firewall pour ssh
      community.general.ufw:
        rule: allow
        name: ssh
        state: enabled

    - name: Régle du Firewall pour squid
      community.general.ufw:
        rule: allow
        port: '3128'
        proto: tcp
        state: enabled
  become: true
  ignore_errors: true
  notify: restart Squid
  when: ansible_facts['os_family'] == "Debian"