# playbooks/ssh.yml
---
- name: Obtenir l'IP publique sur localhost
  import_playbook: get_public_ip.yml

- name: Configurer SSH sur les serveurs distants
  hosts: ssh 
  become: yes
  gather_facts: true
  
  roles:
    - ssh
