# playbooks/ssh.yml
---
- name: Obtenir l'IP publique sur localhost
  import_playbook: get_public_ip.yml

- name: Configurer SSH sur les serveurs distants
  hosts: ssh 
  become: yes
  gather_facts: true
  vars:
    public_ip_address: "{{ hostvars['localhost']['public_ip_address'] }}"
    private_ip_address: "{{ hostvars['localhost']['private_ip_address'] }}"
  roles:
    - ssh
