---
- name: Installation des PAQUETS
  community.general.apk:
    name: [mc, tree, net-tools, htop, neofetch, wget, ufw, ncdu, nmap]
    state: latest
    update_cache: true
  when: ansible_distribution == "Alpine"